name: bad_socket
description: Add constrains to your Socket to simulate realworld network connections.
version: 0.1.1
homepage: https://github.com/xtyxtyx/bad_socket
author: xuty <xty50337@hotmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
