name: bad_socket
description: bad_socket
version: 0.1.0
homepage: https://github.com/xtyxtyx/bad_socket
author: xuty <xty50337@hotmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
